title: Dragana Photography
default_lang: en
author:
  name: 'Dragana Pijnappel'
  email: draganapijnappeldjenisov@gmail.com
taxonomies:
  - category
  - tag
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
